### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by dimagalat** [quietlychris/convolution#3]
Hi Chris,
First of all, thanks for sharing your project, it's a very cool library.
I was wondering if you could include a LICENCE file in your repo? 
Thanks,
Dima

**Comment by dimagalat** [comment]
@quietlychris tagging, in case you didn't see the issue.

**Comment by quietlychris** [comment]
@dimagalat Sorry for the delay; I took some time off over the past few months from open source contribution, and am just getting started. Not sure if you still have a use for it, but I've licensed this repo under the MIT License.

**Comment by dimagalat** [comment]
All good, I found a way forward. 
Thanks for adding it Chris! I'm sure it might come in handy for someone.
